require: rubocop-rspec

AllCops:
  DisplayCopNames: true

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - memoria.gemspec

Metrics/LineLength:
  Max: 120

# ----------------------- RSpec -----------------------

RSpec/NestedGroups:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
